FROM python:3.11.9

RUN python -m pip install --upgrade pip

ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG GOOGLE_APPLICATION_CREDENTIALS

ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_PORT=$POSTGRES_PORT

VOLUME [ "/data" ]

WORKDIR /cloud

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

ADD $GOOGLE_APPLICATION_CREDENTIALS credentials.json

CMD [ "python", "app/main.py"]



