version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - "./cloud_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - "4345:5432"
    networks:
      - custom_network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: cloud@uniandes.edu.co
      PGADMIN_DEFAULT_PASSWORD: 12345678
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - custom_network

  # redis:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --save 20 1 --loglevel warning
  #   volumes:
  #     - cache:/data
  #   networks:
  #     - custom_network

  # flask:
  #   image: santiago9913/flask:latest
  #   restart: always
  #   command: sh -c "nohup flask run --host=0.0.0.0 > log.txt 2>&1 & celery --app tareas.tareas.celery worker --loglevel=info"
  #   ports:
  #     - "8080:5000"
  #   volumes:
  #     - celery_volume:/usr/src/app
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - custom_network

networks:
  custom_network:
    driver: bridge

volumes:
  pgadmin-data:
  # cache:
  # celery_volume:
