name: Build Image

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor }}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        run: |
          docker buildx build --push \
          --tag ghcr.io/santiago9913/cloud:latest \
          --build-arg POSTGRES_USER=${{secrets.POSTGRES_USER}} \
          --build-arg POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} \
          --build-arg POSTGRES_DB=${{secrets.POSTGRES_DB}} \
          --build-arg POSTGRES_HOST=${{secrets.POSTGRES_HOST}} \
          --build-arg POSTGRES_PORT=${{secrets.POSTGRES_PORT}} \
          --platform linux/amd64,linux/arm64 .
  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "google-github-actions/auth@v2"
        with:
          service_account: ${{secrets.GCP_SA_EMAIL}}
          token_formt: "access_token"
      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: ghcr.io/santiago9913/cloud:latest
          region: us-central1
          service: cloud
